### PR TITLE
Allow documenting route parameters

### LINKED ISSUE #167: support documentation for path parameters
> *Disclaimer: Sorry for opening yet another issue, please close if out of scope/not useful. I'm currently integrating this library into a project that previously had a hand-written openapi doc, so I'm creating an issue here everytime I encounter a situation where the library doesn't (yet) allow what can be achieved by hand.*

It would be cool if the library provided a way to add docs for path parameters. I'm not sure where exactly one would put the corresponding JSDoc comments, maybe in the `Route`s main comment block, as is already the case for annotations to `@response` codes.

### PR DESCRIPTION
**Pull request by wilbrt**
Fixes #167

### CODE REVIEW

**Comment by akheron** [comment]
Parameters can have non-unique names, as long as they appear in a different "parts" of the request.

From the OpenAPI spec:
> **4.8.12 Parameter Object** [§](https://spec.openapis.org/oas/latest.html#parameter-object)
> Describes a single operation parameter.
>
> A unique parameter is defined by a combination of a [name](https://spec.openapis.org/oas/latest.html#parameterName) and [location](https://spec.openapis.org/oas/latest.html#parameterIn).
>
> [...]
>
> 
> in | string | REQUIRED. The location of the parameter. Possible values are "query", "header", "path" or "cookie".

There are two options for solving this:
1. Instead of a single `@reqparam` tag, add separate tags `@query`, `@header`, `@routeParam`, `@cookie` to document parameters appearing in different places. (I used `@routeParam` instead of `@path` because typera exposes captured route parts in `request.routeParams`).
2. Add a more generic `@param IN NAME DESCRIPTION`. The `IN` part would be either `query`, `header`, `path`, or `cookie`, as per the OpenAPI spec.

I don't really have an opinion about which one is better.

**Comment by wilbrt** [comment]
Ah, I wasn't aware of that. The @reqparam tag has now been split into @query, @header, @routeParam and @cookie as suggested.

**Comment by akheron** [comment]
Great stuff!

One more thing: This now seems to set `schema.example` instead of `description` 🤔 There would also be `example` on the "top level" of the parameter.

Eventually users would probably want to set either `description` or `example` or both. I'm not sure how to solve this in a clean way. Adding JSDoc tags for descriptions and examples adds quite a bit of noise.

**Comment by wilbrt** [comment]
Works now as planned,I think. Not 100% sure about the current routeParam validation implementation.

**Pull request merged**
