### PR TITLE
make content-type configurable with custom middleware

### PR DESCRIPTION
**Pull request by dev-m1-macbook**
(related: https://github.com/akheron/typera/issues/306 )

this pull-request makes content-type configurable through custom middleware.

### CODE REVIEW

**Comment by akheron** [comment]
Good work! I wonder why you ended up naming the property `content-type` instead of `contentType`?

**Comment by akheron** [comment]
It would also make sense to provide body parsing middlewares by typera, to not require all users to make their own.

**Comment by dev-m1-macbook** [comment]
> Good work! I wonder why you ended up naming the property content-type instead of contentType?

well I didn't think clearly back then (was like 4:30am here) -- I'll fix this

> It would also make sense to provide body parsing middlewares by typera, to not require all users to make their own.

I'll work on it after this!
btw, there's a lot of middlewares... [bodyparser](https://www.npmjs.com/package/body-parser) page mentions 5
would it be better to have those wrappers in separate repos? 

and because there are too many body-parsing middlewares, it seems that allowing users to provide their own will be much better in terms of flexibility

**Comment by akheron** [comment]
Yeah, of course wrapping existing ones is probably the best option. It's the types and openapi we're really interested here, the purpose is not to write everything from scratch :)

**Comment by akheron** [comment]
Merged, thanks a lot!

**Comment by akheron** [comment]
Released in v2.0.0

**Pull request merged**
